apiVersion: v1
kind: Pod
metadata: 
 name: nginx-pod
 namespace: roboshop-dev
 labels: 
  Env: dev
  Project: roboshop
  Compenent: nginx
 annotations:
  kubectl.kubernetes.io/default-container: nginx
spec: 
 containers:
 - name: nginx
   image: nginx
   ports: 
   - containerPort: 80
   resources:
     requests:
      cpu: "500m"
      memory: "550Mi"
     limits:
      cpu: "500m"
      memory: "900Mi"
 
---

apiVersion: v1
kind: Pod
metadata: 
 name: ubuntu-pod
 namespace: roboshop-dev
 labels: 
  env: dev
  project: roboshop
spec: 
 containers:
 - name: ubuntu
   image: ramatharun/ubuntu:v1
   command: ["sleep","1000"]
  
---
apiVersion: v1 
kind: Pod 
metadata: 
  name: nginx-demo
spec:
 containers:
 -  name: nginx-demo-v1
    image: nginx

---
apiVersion: apps/v1 
kind: Deployment 
metadata: 
 name: frontend
 labels: 
   project: roboshop
   env: dev
spec:
  replicas: 3
  selector:
   matchLabels:
     project: roboshop
     env: dev 
     tier: frontend 
  template: 
   metadata:
    labels:
      project: roboshop
      env: dev 
      tier: frontend
   spec:
    containers: 
    - name: nginx
      image: nginx
---
apiVersion: apps/v1 
kind: Deployment
metadata: 
 name: frontend-dm
 labels: 
  project: roboshop
  env: dev 
spec: 
 replicas: 3
 selector:
  matchLabels: 
   project: roboshop
   env: dev 
   tier: frontend 
 template: 
  metadata: 
   labels: 
    project: roboshop
    env: dev 
    tier: frontend 
  spec: 
   containers: 
    - name: nginx 
      image: nginx
  
---
apiVersion: v1 
kind: Pod 
metadata: 
 name: oracle-client-pod 
spec: 
 containers: 
  - name: oracle-client-pod 
    image:  ramatharun/oralce_client:v1
