apiVersion: v1
kind: Pod
metadata: 
 name: nginx-pod
 namespace: roboshop-dev
 labels: 
  env: dev
  project: roboshop
  compenent: froentend
 annotations:
  kubectl.kubernetes.io/default-container: nginx
spec: 
 containers:
 - name: nginx
   image: nginx
   ports: 
   - containerPort: 80
   resources:
     requests:
      cpu: "500m"
      memory: "550Mi"
     limits:
      cpu: "500m"
      memory: "900Mi"
 
---

apiVersion: v1
kind: Pod
metadata: 
 name: alpine-pod
 namespace: roboshop-dev
 labels: 
  env: dev
  project: roboshop
spec: 
 containers:
 - name: alpine
   image: ramatharun/alpine:v1
   command: ["sleep","1000"]
  
 


