apiVersion: v1
kind: Pod
metadata: 
 name: nginx-pod
 namespace: roboshop-dev
 labels: 
  env: dev
spec: 
 containers:
 - name: nginx
   image: nginx
 - name: almalinux
   image: almalinux
   command: ["sleep","300"]


